### ISSUE TITLE
grandchild of boost union, child of the boost_union_child, to control their own settings

### ISSUE THREAD

**Issue by twjn** [moodle-an-hochschulen/moodle-theme_boost_union_child#2]
I want each grandchild of boost union, child of the boost_union_child, to control their own settings but instead I get a grandchild listing underneath the boost_union_child, like so:

![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/assets/84981414/d3057dbb-bc42-4621-a999-a2412d161c57)

In the image QA is the grandchild.

So if i change any of the settings in the grandchild it also changes the settings in the boost_union_child.  

How do I move the grandchild up one level so it can control just its own settings? 

Thankyou.

**Comment by abias** [comment]
Hi @twjn ,

thanks for asking.

We placed the Boost Union Child settings as a subpage of the Boost Union setting by purpose to make clear that Boost Union Child's settings are _an addition_ to the Boost Union settings.

This placement is happening here: https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/blob/master/settings.php#L117-L118

If you want your Boost Union Child settings to present a settings page on its own, you could have a look at Boost's settings page on https://github.com/moodle/moodle/blob/main/theme/boost/settings.php and re-build the Boost Union Child page in a similar way.

However, I have to say that this approach is out of scope of what we tried to provide with Boost Union Child so we can't provide much more support, I am afraid.

I will just leave this issue open for some more time in case someone from the community wants to discuss more about this approach.

Cheers,
Alex
