### ISSUE TITLE
Include Boost Union config using require instead of require_once

### ISSUE THREAD

**Issue by larsbonczek** [moodle-an-hochschulen/moodle-theme_boost_union_child#3]
In config.php, the Boost Union config should be included using `require`, not `require_once`, to make sure that all Boost Union settings are added to the `$THEME` object even if the Boost Union config was already included in some other place.
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/blob/29d715cfe6815e1d4e65d1cbf4eac56d1c888fa7/config.php#L31-L33

**Comment by abias** [comment]
Thank you for this important note, @larsbonczek.
I changed this behaviour in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/commit/beb3271353c75e0b3c70873fdd20e807559d8799.
