### ISSUE TITLE
Settings tab no longer working by move to ../theme/boost_union/settings_overview.php

### ISSUE THREAD

**Issue by vincentcornelis** [moodle-an-hochschulen/moodle-theme_boost_union_child#4]
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/blob/master/settings.php implementation no longer seems compatible with theme Boost Union.

Before:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/assets/86881597/05ebfe93-ed1d-4a3b-8f6c-a619837f48eb)

After (at least at Boost Union version 2023010561):
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/assets/86881597/cdebc12a-7cc1-4b60-bcc0-ab5cf69bb618)

I'd like to know if there already is a new way of implementing, so we can get a tile in the settings_overview.php page?
Like so perhaps?:
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/assets/86881597/6e550c69-de83-42ae-92f6-d3e005ef0c03)

For now we had to revert back to an older version of Boost Union to keep our settings page available.

**Comment by abias** [comment]
Hi @vincentcornelis ,

maybe you missed our announcement in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/master/CHANGES.md#v43-r11 where we wrote: "Child theme support: If you are running a Boost Union Child theme, please make sure to adapt your child theme to our latest boilerplate."

These latest boilerplate changes are in the commit https://github.com/moodle-an-hochschulen/moodle-theme_boost_union_child/commit/9b6ad9a4dd99a24e0bcdc93514279607d8e9c9b9.

I am quite sure that you can get your Boost Union Child theme working with the latest Boost Union release if you adopt the changes from this commit into your Boost Union Child theme.

If it does not work, please let us know again.

Cheers,
Alex
